### ISSUE TITLE
Cod Abundance in the EBS 

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#10]
cod abundance data by year class, for all stations during the EBS summer surverys from 2014-2021. 

**Data product requested (stratum CPUE, etc.)**:  numerical CPUE by age

**Species**: pcod

**Region** (GOA, AI, Bering Sea): EBS  

**Research team making the request**:  @Erin-Fedewa-NOAA,  Maddie Shipley (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):

**Comment by MargaretSiple-NOAA** [comment]
Per Sean, we don't have abundance by year class for PCOD, but we have it by length and you could use an age-length key to convert the lengths to ages which can get you back to year class. But the age-length relationship varies by year (see page 218 of https://apps-afsc.fisheries.noaa.gov/refm/docs/2021/EBSpcod.pdf). So need to confirm with Madi if she wants to convert the lengths to ages (she can also ask Steve Barbeaux about it).

**Comment by Erin-Fedewa-NOAA** [comment]
@shipmadison bringing you into this issue so Nancy doesn't have to loop back and email ya!

**Comment by shipmadison** [comment]
Hi all! Thanks for all your help with this request. Data of abundance by length class would be totally fine for the purposes of my initial exploration.

**Comment by Lewis-Barnett-NOAA** [comment]
[**@shipmadison**](https://github.com/shipmadison) does [this](https://github.com/afsc-gap-products/data-requests/issues/10#issuecomment-1050397022) satisfy your needs? I'm going to close the issue but if this does not suffice, feel free to respond and reopen.

**Comment by shipmadison** [comment]
@Lewis-Barnett-NOAA, apologies, I clicked your link above to verify, (https://drive.google.com/file/d/18M0M5ZrmGsCNaHdPMyjxl3GeeKzF4Obd/view?usp=sharing) and I'm being denied access to a google drive where I presume the data are. How should I proceed?

**Comment by Lewis-Barnett-NOAA** [comment]
@shipmadison you now have access
