### ISSUE TITLE
PYCNOPODIA REQUEST 

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#12]
** Data Requested:  YEAR, CRUISEJOIN, HAULJOIN ,CATCHJOIN, REGION, VESSEL,CRUISE,STRATUM,STATIONID,HAUL,HAUL_TYPE	
,PERFORMANCE,START_TIME,START_LATITUDE,START_LONGITUDE,BOTTOM_DEPTH,SURFACE_TEMPERATURE,GEAR_TEMPERATURE,EFFORT,SPECIES_CODE,WEIGHT,wCPUE,NUMBER_FISH,nCPUE,SUBSAMPLE_CODE	VOUCHER 

**_Pycnopodia helianthoides_ species_code = 80160**:

**Region** (GOA, AI, Bering Sea):

**2022 Request:  Duane Stevenson "Could you provide a new data set with the same parameters of the one given to Gravem et al., but with the most recent surveys included?"

History:  2020 Original request was fufilled by Jason Conner and submitted to Sara by Nancy: " Hello, my name is Sara Hamilton. I’m writing on behalf of myself and my colleague Dr. Sarah Gravem, who have been contracted by The Nature Conservancy to conduct an IUCN Red List Assessment for _Pycnopodia helianthoides_. 
We need to estimate _Pycnopodia_ population densities across their entire range, both before the catastrophic outbreak in 2014/2015 and post outbreak. Since _Pycnopodia_ go down to depths of around 600m, we are gathering trawl data to assess the population density at non-diveable depths. I found the Alaska Groundfish Bottom Trawl data (which includes sightings of Pycnos) on the AFSC website (https://www.fisheries.noaa.gov/alaska/commercial-fishing/alaska-groundfish-bottom-trawl-survey-data). 

This data will be quite useful to us, particularly since it has a Weight CPUE metric. This data provides us with evidence of presence of _Pycnopodia_, but doesn’t tell us much about absence (aka, the stations that were trawled and no Pycnos were found). Is there any way you could help me find a trawl dataset that lists all the bottom trawls and an estimated area swept for each? If not, is there anyone you can suggest that might be able to help me? Any suggestions are greatly appreciated!  Sara Hamilton (she/her) NSF-GRFP PhD Candidate  Oregon State University  540-292-4313 https://hamiltsa9.wixsite.com/kelp"

[Pycnopodia.csv](https://github.com/afsc-gap-products/data-requests/files/8255656/Pycnopodia.csv)
**HISTORY:  provide a new data set with the same parameters of the one given to Gravem et al., but with the most recent surveys included

**Comment by Jason-Conner-NOAA** [comment]
Requested output emailed to @Duane-Stevenson-NOAA
