### ISSUE TITLE
NBS_Numerical CPUE by station all species

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#15]
**Data product requested:** Numerical CPUE by station (full timeseries)

**Species:** all

**Region: **NBS

**Research team making the request:** **Shellfish Assessment Program** @Erin-Fedewa-NOAA @mikelitzow 
 datasets for a manuscript as well as the snow crab Ecosystem and Socioeconomic Profile

**Comment by EmilyMarkowitz-NOAA** [comment]
I corresponded with Erin and sent her the data. Data can be found in this [google drive](https://drive.google.com/drive/folders/1xtyskd9wx4FA_ibjDswIyX9Be8Yy8poo?usp=sharing) folder and the code for this can be found at this [repo](https://github.com/afsc-gap-products/gap_public_data). This data will (SOON!) be shared via the [Fisheries One Stop Shop platform](https://www.fisheries.noaa.gov/foss/f?p=215:200:1194264142708:Mail:NO:::).
