### ISSUE TITLE
EBS Pollock

### ISSUE THREAD

**Issue by lee-qi** [afsc-gap-products/data-requests#18]
**Data product requested (stratum CPUE, etc.)**: 
Model settings and data inputs for the density estimates used in the assessment

**Species**:
Walleye Pollock

**Region** (GOA, AI, Bering Sea):
Bering Sea

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Qi Lee at SAFS, working with @James-Thorson-NOAA and Alan Haynie (alan.haynie@noaa.gov) at AFSC.

**Comment by CaitlinAkselrud-NOAA** [comment]
The standard data and code (including settings) for the VAST 2021 assessment products was delivered to @lee-qi.
