### ISSUE TITLE
Pollock 1 cm estimates for FEAST

### ISSUE THREAD

**Issue by ivonneo** [afsc-gap-products/data-requests#2]
**Data product requested (stratum CPUE, etc.)**: 
Density dependent corrected NumCPUE by year, station and 1 cm length bins 

**Species**:
Pollock

**Region** (GOA, AI, Bering Sea):
EBS + NEBS

**Research team making the request** (PI /requester name if you are not the PI, and tag team members with github accounts):
Resource Ecology and Ecosystem Modeling (REFM), FEAST, Kerim Aydin

**Comment by CaitlinAkselrud-NOAA** [comment]
Provide:
Density-dependent corrected pollock data for:

1. total numbers by year and station
2. total biomass by year and station
3. total numbers by year, station, and 1 cm length bin

Provide write-up of methods
- include: name, affiliation, and preferred acknowledgement for data products

**Comment by CaitlinAkselrud-NOAA** [comment]
These data products were delivered to Ivonne Ortiz, 2022-02-07.
