### ISSUE TITLE
CPUE and numbers of walleye pollock + surface and bottom temp for Bering Sea

### ISSUE THREAD

**Issue by callorhinus** [afsc-gap-products/data-requests#20]
**2021 CPUE biomass and numbers of walleye pollock, near surface temperature and bottom temperature, latitude and longitude for all stratum in the Bering Sea summer bottom trawl survey (stratum CPUE, etc.)**: The same data output made available to the public on NOAA's website.

**Species**: Walleye pollock

**Region** (GOA, AI, Bering Sea):Bering Sea

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):Jeremy Sterling Marine Mammal Laboratory

**Comment by Duane-Stevenson-NOAA** [comment]
Please refer to this test version of the GAP data on the FOSS public data portal:
https://test-www.fisheries.noaa.gov/foss/f?p=215:28

Although the interface subtleties have not been finalized, the data are accessible there now.

**Comment by NancyRoberson** [comment]
Hi @callorhinus, was the FOSS public data portal able meet your request needs?  If not, let us know where you had troubles.  The portal is in test so your feedback is especially important.   If you are satisfied, I will close this ticket.
