### ISSUE TITLE
1983-2021 Surface and Gear Temperature Data

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#23]
**Data product requested (stratum CPUE, etc.)**:   Surface and Gear Temperatures 1983-2021

**Species**: N/A

**Region** Chukchi Sea; EBS slope, EBS shelf; Northern Bering Sea 

**Research team making the request**  kelly.kearney@noaa.gov

**RESULTS and COMMENTS**
[KEARNEY_GROUNDFISH SURVEY TEMPERATURE DATA_1983-2021.xlsx](https://github.com/afsc-gap-products/data-requests/files/8671568/KEARNEY_GROUNDFISH.SURVEY.TEMPERATURE.DATA_1983-2021.xlsx)

I used Oracle SQL below to query the temperature data. 
1983 was the start point because we didn't employ standard methods for temperature measurements prior. 
6 =Chukchi Sea Trawl Survey; 78=Eastern Bering Sea Slope Bottom Trawl Survey
98=Eastern Bering Sea Crab/Groundfish Bottom Trawl Survey; 143=Northern Bering Sea Crab/Groundfish Survey - Eastern Bering Sea Shelf Survey Extension
Abundance Haul YES means that it was a satisfactory haul and the data are can be used in abundance estimates.  NO means that the haul was not satisfactory and the data shouldn't be used in abundance estimates.  Both types are in the results.  
18,422 records were returned.

SELECT
    region,
    cruise,
    vessel,
    haul,
    to_char(start_time, 'YYYY-MM-DD HH24:MI:SS')      start_time,
    surface_temperature                               surface_temperature_celsius,
    gear_temperature                                  gear_temperature_celsius,
    abundance_haul                                     
FROM
    racebase.haul
WHERE
    cruisejoin IN (
        SELECT
            racebase_cruisejoin
        FROM
            race_data.cruises
        WHERE
            survey_id IN (
                SELECT
                    survey_id
                FROM
                    race_data.surveys
                WHERE
                    survey_definition_id IN 
                    ( 98, 78, 143, 6 ) 
                    AND year > 1982))

**Comment by NancyRoberson** [comment]
Emailed results to PI

**Comment by kakearney** [comment]
Can I update this request to include additional data fields for each entry?  The fields listed below were included in the previous (1982-2019) data file, and ideally I'd like to replicate that file with the addition of 2021 data.  The fields with an asterisk are those that are specifically used in the regional model surface/bottom temperature validation process (as described in [Kearney (2021)](https://repository.library.noaa.gov/view/noaa/28763)).

CRUISEJOIN
HAULJOIN
REGION
VESSEL*
CRUISE*
HAUL*
HAUL_TYPE*
PERFORMANCE*
START_TIME*
DURATION
DISTANCE_FISHED
NET_WIDTH
NET_MEASURED
NET_HEIGHT
STRATUM*
START_LATITUDE*
END_LATITUDE*
START_LONGITUDE*
END_LONGITUDE*
STATIONID*
GEAR_DEPTH*
BOTTOM_DEPTH*
BOTTOM_TYPE
SURFACE_TEMPERATURE*
GEAR_TEMPERATURE*
WIRE_LENGTH
GEAR
ACCESSORIES
SUBSAMPLE
ABUNDANCE_HAUL
AUDITJOIN

Thank you!

**Comment by NancyRoberson** [comment]
Hi Kelly,
You bet.  Attached is are the results including additional fields.
As usual, please look them over for correctness and let me know if you need more information.

Thanks!
Nancy

[KEARNEY_GROUNDFISH SURVEY TEMPERATURE DATA_1983-2021_ additional fields.xlsx](https://github.com/afsc-gap-products/data-requests/files/8701197/KEARNEY_GROUNDFISH.SURVEY.TEMPERATURE.DATA_1983-2021_.additional.fields.xlsx)

**Comment by kakearney** [comment]
Can I get an update for 2022?  No changes to the details other than adding a year.

**Comment by Lewis-Barnett-NOAA** [comment]
Hi Kelly, it may not include all your fields, but the coldpool package is updated with the raw temperature data: https://raw.githubusercontent.com/afsc-gap-products/coldpool/main/data/index_hauls_temperature_data.csv
