### ISSUE TITLE
Sleeper Shark Weight/ Measurements and Capture Info [Data product request]

### ISSUE THREAD

**Issue by K-Fuller** [afsc-gap-products/data-requests#26]
**Data product requested (stratum CPUE, etc.)**: 
Physical data taken of caught sleeper sharks, as well as the associated catch data (location, time, etc)

**Species**:
Pacific sleeper shark

**Region** (GOA, AI, Bering Sea):
All

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Keith Fuller, NOAA affiliate and APU Postdoc, working with Cindy Tribuzio (of MESA), Craig Rose, and Brad Harris (of APU)

**Comment by NancyRoberson** [comment]
@K-Fuller, @Duane-Stevenson-NOAA , @Ned-Laman-NOAA 

Please find attached 3 files of sleeper shark data:
catches, haul data for those catches and specimen data.

Briefly, there are 569 recorded catches of sleeper sharks in our database and the dates span from 1980-2021.
There are 291 records of specimen data and they span from 1996 to 2016 (I am unclear why there aren't records for more recent years).

Please note that the catch data include standard GAP surveys as well as historic records from other regions and
surveys.   The standard surveys are Aleutian Islands, Bering Sea and Gulf of Alaska.  The historic regions and surveys are West Coast (WC) Hydroacoustic Bering Sea (HBS), Hydroacoustic Gulf of Alaska (HG), Hydroacoustic West Coast (HWC).  


[KFuller_github_26_SleeperShark_SpecimenData.xlsx](https://github.com/afsc-gap-products/data-requests/files/9012310/KFuller_github_26_SleeperShark_SpecimenData.xlsx)
[KFuller_github_26_SleeperShark_HaulData.xlsx](https://github.com/afsc-gap-products/data-requests/files/9012311/KFuller_github_26_SleeperShark_HaulData.xlsx)
[KFuller_github_26_SleeperShark_catches.xlsx](https://github.com/afsc-gap-products/data-requests/files/9012313/KFuller_github_26_SleeperShark_catches.xlsx)
