### ISSUE TITLE
1982 - Present Specimen Data Request

### ISSUE THREAD

**Issue by jennybigman** [afsc-gap-products/data-requests#27]
**Data product requested (stratum CPUE, etc.): specimen data (sex, length, weight, age, + metadata (survey, cruise, region, stratum, haul, station ID, lat/long, bottom temp, surface temp, species code, species ID, tow_date))

**Species: All species

**Region: EBS, GOA, AI

**Research team making the request: Jennifer Bigman, EcoFOCI

* I am happy to include as many co-authors/collaborators as appropriate on this project.
* I wasn't exactly sure the time frame in which these data would be available. If possible, I would like data from all years that exist. Thank you!!

**Comment by Lewis-Barnett-NOAA** [comment]
Jenny, [here ](https://drive.google.com/drive/folders/1vJQNN98iN6c7jTD5RNbXrvvOCFQaTRdx?usp=sharing )is the data we discussed

**Comment by jennybigman** [comment]
Thank you!
