### ISSUE TITLE
IPHC annual request:  2022 EBS/AI/NBS haul, catch, and length data for Pacific halibut

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#29]
**Data product requested**  (haul data, catch data, length data): 

**HAUL**:
- CRUISEJOIN/HAULJOIN 
-   REGION 
-   VESSEL/CRUISE/ HAUL 
-   HAUL_TYPE 
-   PERFORMANCE
-   START_TIME 
-   DURATION
-   DISTANCE_FISHED 
-   NET_WIDTH 
-   NET_MEASURED
-   NET_HEIGHT 
-   STRATUM 
-   START_LATITUDE/END_LATITUDE 
-   START_LONGITUDE/END_LONGITUDE 
-   STATIONID 
-   GEAR_DEPTH/BOTTOM_DEPTH
-   BOTTOM_TYPE 
-   SURFACE_TEMPERATURE/GEAR_TEMPERATURE
-   WIRE_LENGTH 
-   GEAR 
-   ACCESSORIES
-   SUBSAMPLE 
-   AUDITJOIN

**CATCH**:
- CRUISEJOIN/ HAULJOIN/CATCHJOIN
- REGION
- VESSEL/CRUISE/HAUL
- SPECIES_CODE
- WEIGHT
- NUMBER_FISH
- SUBSAMPLE_CODE
- VOUCHER
- AUDITJOIN

**LENGTHS**:

- CRUISEJOIN/HAULJOIN/CATCHJOIN
- REGION
- VESSEL/CRUISE/HAUL
- SPECIES_CODE
- LENGTH
- FREQUENCY
- SEX 
- SAMPLE_TYPE
- LENGTH_TYPE
- AUDITJOIN

**Species requested**   (Pacific halibut): 
**Region**  (EBS Shelf):

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
IPHC Lauri Sadorus

**Comment by RebeccaHaehn-NOAA** [comment]
@NancyRoberson and Lauri.Sadorus@iphc.int
Data for EBS and NBS have been sent directly to Lauri on Sept 26, 2022. Data have also been uploaded into the [Google Drive](https://drive.google.com/drive/folders/1hfNhfOmIDC7dSigbsz4P3amZWj4jMv_u) associated with this GitHub.

**Comment by NancyRoberson** [comment]
@RebeccaHaehn-NOAA and Lauri.Sadorus@iphc.int
AI haul, catch, and length data have been sent directly to Lauri on Sept. 20, 2022.  
Data have also been uploaded into the [Google Drive](https://drive.google.com/drive/folders/1hfNhfOmIDC7dSigbsz4P3amZWj4jMv_u) associated with this GitHub.
