### ISSUE TITLE
2022 EBS CPUE By Station For All Species 

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#30]
**Data product requested (stratum CPUE, etc.)**: 
EBS shelf CPUE by station

Including:

- Vessel/Cruise/Haul
- Latitude
- Longitude
- Station
- Stratum
- Year
- Datetime
- WTCPUE
- NUMCPUE
- Common_name
- Scientific_Name
- Species_code
- Bottom_Depth
- Bottom_Temperature
- Surface_temperature	

**Species**:
All species caught

**Region** (GOA, AI, Bering Sea):
EBS shelf

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Erin.Fedewa@noaa.gov  Kodiak Fisheries Research Center

**Comment by RebeccaHaehn-NOAA** [comment]
[Erin.Fedewa@noaa.gov](mailto:Erin.Fedewa@noaa.gov) Kodiak Fisheries Research Center.
This request has been completed. Data are located in the [Google drive](https://drive.google.com/drive/folders/1hfNhfOmIDC7dSigbsz4P3amZWj4jMv_u) associated with this GitHub. The data are also available on the AFSC Public Drive in the dropbox. Please see email sent by @Duane-Stevenson-NOAA on September 14th.
