### ISSUE TITLE
[Data product request] - MACE, EBS

### ISSUE THREAD

**Issue by abigailatsea** [afsc-gap-products/data-requests#33]
Hello- 
We'd like the **Length at age data for summer EBS survey**:
Unclear on what "stratum" means, but we'd like data from legs 1-3. 
Time-frame- by 10/13 if at all possible. 

**Walleye Pollock**:

** Bering Sea **:

MACE, Sarah Stienessen, sarah.stienessen@noaa.gov

Thanks!

**Comment by MargaretSiple-NOAA** [comment]
Hi Abigail, sorry I just saw this. I am not an EBS person so I have just added a tag so someone will pick it up.

**Comment by abigailatsea** [comment]
Hi Megsie-
Wasn't sure who to tag, when Sarah emailed asking for the data she was told to submit an issue here. Thanks for answering!

**Comment by Duane-Stevenson-NOAA** [comment]
Abby and Sarah,

Please see the attached table, generated using the following SQL script:
select *
from RACEBASE.specimen
where CRUISEJOIN in (-755, -756) 
and SPECIES_CODE = 21740;

Let me know if this fulfills your need.

Duane

[EBS2022_POLLOCK_AGES.csv](https://github.com/afsc-gap-products/data-requests/files/9814634/EBS2022_POLLOCK_AGES.csv)

**Comment by Duane-Stevenson-NOAA** [comment]
Can we consider this issue closed now?

Duane

**Comment by abigailatsea** [comment]
Duane-
Thanks, yes we can.
