### ISSUE TITLE
FMP codes for forage and protected species: add to RACE_DATA.FMA_SPECIES_CODES?

### ISSUE THREAD

**Issue by mike-levine** [afsc-gap-products/data-requests#34]
**Data product requested (stratum CPUE, etc.)**:  add species to RACE_DATA.FMA_SPECIES_CODES?

**Species**: Multiple

**Region** (GOA, AI, Bering Sea): NA

MACE submits an annual report to the AK Regional Office accounting for our catch of 'Fishery Management Plan species'. We've long worked off a list at *racebase_dev.fmp_species_list* but Taina noticed this list was incomplete. We requested a current 2022 list from Cathy Tide, AK Regional Office <cathy.tide@noaa.gov>.

Nancy Roberson suggested using the list at RACE_DATA.FMA_SPECIES_CODES; a comparison between the 2022 'FMP list' from Cathy Tide and the list maintained at  RACE_DATA.FMA_SPECIES_CODES finds 59 species that are present on the 'FMP list'  that aren't present on the RACE_DATA.FMA_SPECIES_CODES list. Those 59 are linked [here](https://docs.google.com/spreadsheets/d/1hJ2jAhq_kfnVSSKMbsKWGz2Qjj6EPL_I1vlcELaIYkg/edit#gid=1717346057) in a google sheet to save space.

Would it be possible to add these species? I suppose, if so, we'd simply refer to the list at RACE_DATA.FMA_SPECIES_CODES for our annual reporting needs (and remember to update as needed).

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Mike Levine, MACE @mike-levine
Taina Honkalehto, MACE <taina.honkalehto@noaa.gov>

**Comment by NancyRoberson** [comment]
@mike-levine ,
Hi!  In order to add these 59 species to RACE_DATA.FMA_SPECIES_CODES, I will need the FMA_SPECIES_CODES for them.  Can you provide them to me?  
Thank you!

**Comment by NancyRoberson** [comment]
Hi Mike,
Here is a list all of the FMA species codes from their species table, provided by Chris Anderson -  if you could you cull out the ones you for the species you want to add and send them to me, I will try to get this done this week. 

Thanks so much,
Nancy

[fma_species_codes (1).xlsx](https://github.com/afsc-gap-products/data-requests/files/10058362/fma_species_codes.1.xlsx)

**Comment by mike-levine** [comment]
Thanks, Nancy,

I gave this a go, but I think the issue is that there are many species included in the RACE list that just don't have an FMA species code. I added a few columns [here](https://docs.google.com/spreadsheets/d/1hJ2jAhq_kfnVSSKMbsKWGz2Qjj6EPL_I1vlcELaIYkg/edit#gid=1717346057) with what I could match up. 

I guess it isn't surprising that uncommonly encountered species (lots of sculpin species, mainly) don't have an FMA code, as from what I remember as an observer, many of the sculpins just get called 'sculpin unident).

I guess, given this, it might not work to update RACE_DATA.FMA_SPECIES_CODES. Without an FMA code on most of these species, I don't see how it could exist on the table?

**Comment by NancyRoberson** [comment]
Thanks Mike,  
I agree that without FMA codes, this won't work;  they are the primary codes for the table.

Re:  the one's you were able to match up are in FMA_SPECIES_CODES table.

Going forward,  if/when FMA assigns codes to the orphans, submit them as an issue and I/GAP staff will update them in the table.
