### ISSUE TITLE
EBS slope survey stratum shapefiles

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/data-requests#38]
**Data product requested (stratum CPUE, etc.)**: EBS Slope survey shapefiles for use in 2022 stock assessment

**Species**: N/A

**Region** (GOA, AI, Bering Sea): Bering Sea

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.): Jane Sullivan(@JaneSullivan-NOAA) and Matt Callahan (@MattCallahan-NOAA)

**Comment by sean-rohan-NOAA** [comment]
Worked with Jerry to get EBS Slope stratum and survey area shapefiles included in version 2.1.0 of akfishcondition:
[https://github.com/afsc-gap-products/akgfmaps](https://github.com/afsc-gap-products/akgfmaps)

Example code for using the akgfmaps::get_base_layers() function to access the shapefiles in R:

library(akgfmaps)
library(ggthemes)

slope_layers <- akgfmaps::get_base_layers(select.region = "ebs.slope", set.crs = "EPSG:3338")

ggplot() +
  geom_sf(data = slope_layers$survey.area) +
  geom_sf(data = slope_layers$akland) +
  geom_sf(data = slope_layers$graticule, alpha = 0.7) +
  coord_sf(slope_layers$plot.boundary$x,
           slope_layers$plot.boundary$y) +
  scale_x_continuous(breaks = slope_layers$lon.breaks) +
  scale_y_continuous(breaks = slope_layers$lat.breaks) +
  theme_few() +
  theme(legend.position = "none")

ggplot() +
  geom_sf(data = slope_layers$survey.strata,
          mapping = aes(fill = factor(STRATUM)),
          color = NA) +
  geom_sf(data = slope_layers$akland) +
  geom_sf(data = slope_layers$graticule, alpha = 0.7) +
  coord_sf(slope_layers$plot.boundary$x,
            slope_layers$plot.boundary$y) +
  scale_x_continuous(breaks = slope_layers$lon.breaks) +
  scale_y_continuous(breaks = slope_layers$lat.breaks) +
  theme_few() +
  theme(legend.position = "none")

table(slope_layers$survey.strata$STRATUM)

agg_strata <- slope_layers$survey.strata |>
  dplyr::group_by(STRATUM) |>
  dplyr::summarise()

ggplot() +
  geom_sf(data = agg_strata,
          mapping = aes(fill = factor(STRATUM)),
          color = NA) +
  geom_sf(data = slope_layers$akland) +
  geom_sf(data = slope_layers$graticule, alpha = 0.7) +
  coord_sf(slope_layers$plot.boundary$x,
           slope_layers$plot.boundary$y) +
  scale_x_continuous(breaks = slope_layers$lon.breaks) +
  scale_y_continuous(breaks = slope_layers$lat.breaks) +
  theme_few() +
  theme(legend.position = "none")

table(agg_strata$STRATUM)

slope_layers$survey.strata |>
  dplyr::mutate(area = sf::st_area(slope_layers$survey.strata)) |>
  dplyr::group_by(STRATUM) |>
  dplyr::summarise(total_area = sum(area))

agg_strata |>
  dplyr::mutate(area = sf::st_area(agg_strata)) |>
  dplyr::group_by(STRATUM) |>
  dplyr::summarise(total_area = sum(area))

ggplot() +
  geom_sf(data = slope_layers$bathymetry,
          mapping = aes(color = factor(METERS))) +
  geom_sf(data = slope_layers$akland) +
  geom_sf(data = slope_layers$graticule, alpha = 0.7) +
  coord_sf(slope_layers$plot.boundary$x,
           slope_layers$plot.boundary$y) +
  scale_x_continuous(breaks = slope_layers$lon.breaks) +
  scale_y_continuous(breaks = slope_layers$lat.breaks) +
  scale_color_brewer(name = "Depth (m)") +
  theme_few()

**Comment by JaneSullivan-NOAA** [comment]
Thanks @sean-rohan-NOAA and Jerry!
