### ISSUE TITLE
RACEBase.CATCH correction[Data product request]

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [afsc-gap-products/data-requests#49]
We've identified an error in RACEBase.CATCH for a record in the GOA 2009 survey aboard Vesteraalen.
At HAULJOIN = -5945, the catch record for SPECIES_CODE = 420 w/weight 0.088 should be changed to SPECIES_CODE = 421 (otherwise that would be a really really small big skate!)

![Capture](https://user-images.githubusercontent.com/50336523/207649658-409e5916-de0d-4270-a3bd-1916355d4207.JPG)

**Comment by NancyRoberson** [comment]
Hi Ned,
[Tabular Form.csv](https://github.com/afsc-gap-products/data-requests/files/10239706/Tabular.Form.csv)

The correct species code (421) is actually in the EDIT table but in order for it to show up in the final tables,  the cruise needs to be finalized. There are ~ 36 level-50 error checks that need to be checked off before I can finalize it.  
Will you look over the attached errors and let me know if I can check them off?   Thanks -N

**Comment by Ned-Laman-NOAA** [comment]
All can be checked of EXCEPT line 32 where the Stratum is null. That should be corrected. I'll try to look into that fix later today.

**Comment by NancyRoberson** [comment]
Thanks and will do.  Let me know when you are finished and I will proceed to finalize the cruise unless you want that job.

**Comment by NancyRoberson** [comment]
Species code updated to 421.

**Comment by Ned-Laman-NOAA** [comment]
To reiterate the above, all 36 of the Level 50 errors can be checked off. The one at line 32 in the csv was a test tow so it validly has a null stationid and stratum and can be checked off as well. 
As for the 421 species_code, I believe you'd indicated that for the change to take between the Edit Table and the Final version there needed to be a change to the coding in the background. Has that happened?
I tried checking out the data to update and finalize, but am not authorized. Let me know if you want to just take care of this yourself or grant me privileges to this cruise so I can do it.

**Comment by NancyRoberson** [comment]
I have taken care of this - data has been corrected and cruise finalized so I will close this issue.
