### ISSUE TITLE
[Data product request] Salmon Shark data

### ISSUE THREAD

**Issue by coleary-noaa** [afsc-gap-products/data-requests#5]
**Data product requested (stratum CPUE, etc.)**: 
tow data (length, weight, sex, haul location, gear type, date/time, gear depth) 

**Species**:
Salmon Shark

**Region** (GOA, AI, Bering Sea):
all (GOA, AI, and Bering Sea)

**timespan**:
1982 - present 

**Research team making the request** (PI /requester name if you are not the PI, and tag team members with github accounts):
Sabrina Garcia (ADF&G)

**Comment by coleary-noaa** [comment]
Shared a first data pull [here](https://drive.google.com/drive/folders/1A9G5Uy7ik-mCxDJAApcv1fE-JeCX02Xd?usp=sharing)

created a racebase data pull function in R on my github repo, can push that if we decide to use the same R functions across GAP for data pulls

**Comment by coleary-noaa** [comment]
Look in to 2002 (Stalemate Bank) and 1988 (Bering Sea) observations - outliers 

![map_data_check_by_year](https://user-images.githubusercontent.com/64496320/151254618-8102012f-0d6c-4387-b982-915795c2f109.png)

**Comment by Lewis-Barnett-NOAA** [comment]
closing as this appears to be fulfilled
