### ISSUE TITLE
RACEBase.CATCH correction:  Big skate or skate egg cases?

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#50]
**Data product requested (stratum CPUE, etc.)**: 

There is a mismatch between the catch records for big skate in RACEBASE.CATCH and the CPUE records in GOA.CPUE. 

![Capture](https://user-images.githubusercontent.com/17622896/208712576-73f442ef-954a-4d59-9236-748f757e962f.JPG)

 I am wondering whether there were some big skate eggs that were merged with or misID'd as the big skate species code in the RACEBASE.CATCH table that were then removed/modified from the GOA.CPUE tables. 

Can you check the big skate records in the attached in the spreadsheet  

**Species**:  Big skate species_code 420

**Region**:  GOA

**Research team making the request** @zoyafuso-NOAA

**Comment by NancyRoberson** [comment]
![Capture2](https://user-images.githubusercontent.com/17622896/208725881-6847cf6a-e0cb-41ad-b2f5-bc25ca89501a.JPG)

**Comment by NancyRoberson** [comment]
Hi Zach,
These are my cursory findings.  Ned, what are your thoughts and directions going forward?
Thanks

**Comment by NancyRoberson** [comment]
I forgot to attach spreadsheet and the catch photo from 2009 vessel 159 haul 257.  Here they are:

![2009_ 159_257JPG](https://user-images.githubusercontent.com/17622896/208726933-9148f0fa-a0ae-4e16-be4b-e2ab8db62ec6.JPG)
[Big Skate Check.xlsx](https://github.com/afsc-gap-products/data-requests/files/10270685/Big.Skate.Check.xlsx)

**Comment by NancyRoberson** [comment]
@Ned-Laman-NOAA 

Hi Ned,
Shall I update the records to 421 or leave as they are?

**Comment by Ned-Laman-NOAA** [comment]
When we talked about this last we both agreed that the smaller weights were to be changed to 421, right? Something to do with a bit of merge code buried in GIDES (or was that another issue?).

**Comment by NancyRoberson** [comment]
Hi Ned,

You are right and the problem has now been corrected:  

In the **RACE_DATA.RACE_SPECIES_CODES** table, the **"Merge in RACEBASE"** flag was set = **'Y**' for species_code **421**.(see image below) This meant that the data merged with the parent code (**420**), when extracted for RACEBASE. 

When **'Merge in RACEBASE"** was  changed to **'N'**,  and the source materialized views were refreshed (see package procedure below), all of the **421**'s  unmerged.  The **421** species codes, counts and weights now show up in the catch records (see table below) along with the correct number and weights of **420**


![Capture (1)](https://user-images.githubusercontent.com/17622896/215597745-6dc12fbb-b5d5-4a6b-b0be-56be812149a9.JPG)

Package Procedure:
begin
   racebase_mview_utils.refresh_mview(p_mview_name_in => 'CATCH');
end;
/

![Capture](https://user-images.githubusercontent.com/17622896/215601962-d082fe8f-e4dc-433c-95dc-1991c58a16aa.JPG)
