### ISSUE TITLE
JOIN_FOSS_CPUE_CATCH missing rows and a column

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/data-requests#52]
Thanks for separating out the haul and catch data for users to merge externally. 2 quick things:

1) When I try to query the JOIN_FOSS_CPUE_CATCH table from Oracle, I'm only getting 49567 records, so many are missing.  No errors about connection timeouts or anything like that.

2) I know we will be revising the itis codes, but including them in the catch table would be helpful in the meantime

**Comment by EmilyMarkowitz-NOAA** [comment]
Thanks for this, @Lewis-Barnett-NOAA. In the future can you @ me so I can see the issue? I'm not actually sure what happened, but I _think_ it is fixed now. Maybe I  mistakenly uploaded a bad/old version of the table before? I am re-uploading the tables now (may take a day or so) and we can check next week to see if the new join tables on oralce are ok.  

For reference, on my local machine, the tables seem fine (right?): 

The full zero-filled table
```
dim(FOSS_CPUE_ZEROFILLED)
[1] 36317744       37
```

# The unique haul observations
```
dim(JOIN_FOSS_CPUE_HAUL) 
[1] 31608    24
```

# The unique catch observations
```
dim(JOIN_FOSS_CPUE_CATCH)
[1] 36317744       13
```

# Join the haul and catch data to see if there are the same number of dimensions as FOSS_CPUE_ZEROFILLED
```
check <- dplyr::right_join(x = JOIN_FOSS_CPUE_HAUL, 
                           y = JOIN_FOSS_CPUE_CATCH, 
                           by = c("HAULJOIN"))
dim(check)
[1] 36317744       37
```

Hopefully, we'll be able to confirm that this is all sorted next week!

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks @EmilyMarkowitz-NOAA

I was just checking it now and it appears the catch table isn't there at all.  Maybe still processing, or are you revising it?

**Comment by Lewis-Barnett-NOAA** [comment]
Okay, I verified that the tables have everything now, thanks @EmilyMarkowitz-NOAA !
