### ISSUE TITLE
[Data product request]

### ISSUE THREAD

**Issue by lciannel** [afsc-gap-products/data-requests#53]
**Data product requested (stratum CPUE, etc.)**: 
Data from Bottom Trawl groundfish survey in EBS and North shelf (when available). Both catch and length data at each sampled station. Th eformat can be similar to that provided in the past, as shown in [this link]([https://drive.google.com/drive/folders/1b2_q36m0upYtqNFIvMQ9I2YiLj3HukEx?usp=sharing](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1b2_q36m0upYtqNFIvMQ9I2YiLj3HukEx%3Fusp%3Dsharing&data=05%7C01%7Clorenzo.ciannelli%40oregonstate.edu%7C34fa4b0f158d4212f92408daf5af8918%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638092431517052991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hQkmocAzZJOh9tDF6wiNznzgqCku68pTrNCkMO720AM%3D&reserved=0)): 

**Species**:
Pacific cod
**Region** (GOA, AI, Bering Sea):
Besring Sea and North shelf (when available)

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Lorenzo Ciannelli, Oregon State University, lorenzo.ciannelli@oregonstate.edu
Sarah Stone, Oregon State University, stonesar@oregonstate.edu

**Comment by Duane-Stevenson-NOAA** [comment]
Hi Lorenzo,

I don't see a link here for format suggestions. Also, are you just requesting 2022 data, or a range of years?

Duane

**Comment by lciannel** [comment]
Thanks Duane, Nancy. Is Sarah Stone (Stone, Sarah ***@***.***>)
also able to access these data?
Sorry Duane I did not respond earlier. We need all years avaiable
(1982-202X) . What Nancy just sent is perfect!
Best, Lorenzo
