### ISSUE TITLE
Survey CPUE by cm size bins

### ISSUE THREAD

**Issue by pdspencer** [afsc-gap-products/data-requests#54]
This request is an extension of a request in 2020 that was submitted on behalf of Hsiao-Hang Tao and handled by Wayne Palsson (I think Rebecca Haehn did much of the programming work). Some of the species are the same as the 2020 request, but Hsiao-Hang is interested in updated data, and well as additional species. Hopefully, the scripts from 2020 are still available.      

**Data product requested (stratum CPUE, etc.)**:

CPUE (number per area fished) by tow and cm size bin

**Species**:  walleye pollock, Pacific cod, northern rock sole, Pacific halibut, arrowtooth flounder, yellowfin sole, starry flounder, Alaska skate, Alaska plaice, Arctic cod, flathead sole, Bering flounder, Greenland turbot, Kamchatka flounder, rex sole, Sablefish

**Region** (GOA, AI, Bering Sea): EBS and NBS

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):

This request is submitted by Paul Spencer (AFSC REFM, paul.spencer@noaa.gov, github account pdspencer) on behalf of  Hsiao-Hang Tao (hsiaohang.tao@gmail.com), an investigator at National Taiwan University, who is investigating temporal changes in size-specific habitat area and overlap of marine fish.

**Comment by Duane-Stevenson-NOAA** [comment]
Hi Paul,

Rebecca has fulfilled this data request, and the data files can be found here:
https://drive.google.com/drive/folders/1CQLH4BUh7b7JTrcG3sy_FoCuJwXCp00c?usp=share_link

Please note that Rebecca has created a "Readme" file that details some important limitations of these data files, particularly with respect to the very small sample sizes encountered for some of the requested species. Please make sure that the data user reads this file and understands these limitations.

Also, note that this is not a standard data output that we produce as part of our survey routine. It's an analysis product that requires the time and expertise of a GAP staff member (in this case Rebecca Haehn). For such analysis products, we generally request that the GAP staff member be included as an author in any research reports or papers that use the analysis products.

Thank you,

Duane
