### ISSUE TITLE
Atka Mackerel Disease Data Product Request

### ISSUE THREAD

**Issue by estum002** [afsc-gap-products/data-requests#56]
**Data product requested:** Any and all data concerning outbreaks of disease in Atka Mackerel (see attached photo) with location and collection day, month, year.

**Species**: Atka Mackerel

**Region** - AI, Bering Sea

**Research team making the request** Emilie Stump

[Atka_disease_photos.pdf](https://github.com/afsc-gap-products/data-requests/files/10693767/Atka_disease_photos.pdf)

**Comment by smcdermo** [comment]
I am not aware of any projects that collect data on this disease.  Is this a recent occurrence and is it prevalent in a lot of fish?

**Comment by estum002** [comment]
I has occurred previously although I do not know when it was first observed in the fishery. External expressions of disease (lesions) are accompanied by reduced firmness of fish muscle, affecting the quality and marketability of the fish. It is seasonally prevalent in warmer months and has recurred in geographically restricted areas year over year for at least 2 years. The reduced quality of the fish affects marketability and sales price, resulting in currently unquantified economic impacts to the fishery. The captain of the vessel I was serving on keeps a record of these outbreaks on his plotter.

**Comment by NancyRoberson** [comment]
Since GAP has no data currently on this phenomenon, I am closing this issue.
