### ISSUE TITLE
add metadata info

### ISSUE THREAD

**Issue by coleary-noaa** [afsc-gap-products/data-requests#6]
Should we add a version of the column explanations (units & code meanings) for racebase somewhere in the readme?

**Comment by Lewis-Barnett-NOAA** [comment]
I added a link to the codebooks, but not sure what the best way would be to provide other metadata.  I was thinking of linking the InPort entry, but I only found one for the [AI survey](https://www.fisheries.noaa.gov/inport/item/22956) and for the [crab data from EBS](https://www.fisheries.noaa.gov/inport/item/17108).

**Comment by NancyRoberson** [comment]
Use 'GAP' in the search To find GAP metadata in Inport.  We standardized our records with AFSC/RACE/GAP in the titles.
