### ISSUE TITLE
Contact information from historical special projects from requesters interested in fish disease or somatic condition of Atka mackerel

### ISSUE THREAD

**Issue by estum002** [afsc-gap-products/data-requests#60]
**Data product requested**: Please examine historical special projects for contact information from any requesters who were interested in fish disease or somatic condition of Atka mackerel.

**Species**: Atka mackerel (Pleurogrammus monopterygius)

**Region** (GOA, AI, Bering Sea): all regions

**Research team making the request** Emilie Stump

**Comment by NancyRoberson** [comment]
Hi Emilie,
The Groundfish Assessment Program has not had special project requests for fish disease or somatic condition in Atka mackerel.  

AFSC used to have a pathobiology lab, now defunct, but they concentrated mostly on bitter crab syndrome, ichthyophonus, and asterophilia.  I checked their old files but didn't see anything related to atka mackerel.   I will keep digging around and let you know if I find anything.

**Comment by estum002** [comment]
Thanks Nancy! I'll take a look into the literature as well and see if I can find anything there. Best, Em
