### ISSUE TITLE
Spiny dogfish length and sex information from Gulf of Alaska Groundfish Trawl

### ISSUE THREAD

**Issue by LindsayDavidson** [afsc-gap-products/data-requests#62]
**Data product requested (stratum CPUE, etc.)**: Samples from GOA Groundfish bottom trawl - sex and length for Spiny dogfish samples 

**Species**: North Pacific Spiny Dogfish (Squalus Suckleyi)

**Time frame**: 1990 - 2022

**Region** (GOA, AI, Bering Sea): GOA

**Research team making the request** (Lindsay Davidson @lindsaydavidson, Philina English @ecophilina, Sean Anderson @seananderson, DFO Groundfish, Nanaimo, BC.

**Comment by Lewis-Barnett-NOAA** [comment]
Hi Lindsay, I put the data for you [here](https://drive.google.com/drive/folders/1GqOtfpDDJt_hd8O7g3_PNIHcTN0XGTHf?usp=sharing)

I gave access to your dfo accounts but let me know if you need me to share with a different email address.

It contains all survey years, but you can match records to any set of hauls you want using the hauljoin field. See the general GAP survey metadata for other details.

**Comment by LindsayDavidson** [comment]
Thanks very much Lewis - could you please resend to my other address. LNK.davidson@gmail.com (I don't have access via my other email). Thanks again.
