### ISSUE TITLE
Blackspotted and rougheye rockfish specimen and haul data from BS,AI,GOA

### ISSUE THREAD

**Issue by carley-henke** [afsc-gap-products/data-requests#64]
**Data product requested (stratum CPUE, etc.)**: 
Weight, Length, Age, sex, cruise information, depth of gear and bottom, date data collected (I would like as many years as there is data, I know that 2009 has data that is public that I have been using so far). 

**Species**:
Blackspotted and rougheye rockfish

**Region** (GOA, AI, Bering Sea):
Gulf of Alaska (regions in past set were Eastern, Kodiak, Western)

**Research team making the request** 
Carley Henke, MS student at University of Nevada, Reno; SoYoung Ryu, PhD, PI of lab group

**Comment by NancyRoberson** [comment]
Hi Carley,
Attached is a spreadsheet of rougheye and blackspotted rockfish data and collected from our bottom trawl surveys.  Each survey has it's own tab - Gulf of Alaska (GOA), Aleutian Islands (AI) and Eastern Bering Sea (BS).  Also included are column metadata and sql scripts.

Note:  prior to 2005, blackspotted and rougheye rockfish were classified as one species and coded 30050.  In the GOA, there were instances of species code 30050 through 2009. 

Look over the data and let me know if you have futher questions.

Thanks so much and good luck with your research!

[Henke_RougheyeBlackspottedRockfish_AllSurveys.xlsx](https://github.com/afsc-gap-products/data-requests/files/11215161/Henke_RougheyeBlackspottedRockfish_AllSurveys.xlsx)
