### ISSUE TITLE
zero-filled CPUE estimates for calculating ESR indicators

### ISSUE THREAD

**Issue by EmilyMarkowitz-NOAA** [afsc-gap-products/data-requests#74]
## Request

**Data product requested (stratum CPUE, etc.)**: zero-filled CPUE estimates for all species and only standard hauls with the following columns: CRUISEJOIN, CRUISE, YEAR, SURVEY_DEFINITION_ID, SURVEY_NAME, VESSEL_ID, VESSEL_NAME, HAULJOIN, SPECIES_CODE, SPECIES_NAME, COMMON_NAME, WEIGHT_KG, COUNT, AREA_SWEPT_KM2, CPUE_KGKM2, CPUE_NOKM2, HAUL, STATION

**Species**: all species

**Region** (GOA, AI, Bering Sea): EBS and NBS

**Research team making the request**: @Erin-Fedewa-NOAA for calculating ESR indicators

**Notes:** @ThaddaeusBuser-NOAA I think you may have also seen this request and I think I may have already taken care of it! 

## Resolve

Final script using AKFIN data (which should hopefully be available in AKFIN soon, if it isn't already?) and data can be found in this [google drive folder](https://drive.google.com/drive/folders/1DsvY-1AZKV2wz31TYiS7g-wYiDOMINBj?usp=drive_link). 

I also realized that you can grab this data, already joined and ready for extracting, from [FOSS](https://www.fisheries.noaa.gov/foss/f?p=215:28:14951401791129:::::) ([documentation](https://afsc-gap-products.github.io/gap_products/content/foss-platform.html); 2023 data will be available on the platform soon) or the FOSS_CATCH and FOSS_HAUL data tables in GAP_PRODUCTS ([documentation](https://afsc-gap-products.github.io/gap_products/content/foss-oracle-r.html); example for this in the attached script). 

Let me know if I can amend the code, add notes to this request, or help in any other way. Hopefully, this code can be a tool, and you'll be able to pull what you need in the future! 

- [ ] @Erin-Fedewa-NOAA, can you close this issue if everything looks good?

**Comment by Erin-Fedewa-NOAA** [comment]
Looks great, thanks Em!

**Comment by Erin-Fedewa-NOAA** [comment]
Also @EmilyMarkowitz-NOAA weird, I'm not even given a choice to close this issue. Maybe because I'm not a collaborator on the repo? You might have to from your end.

**Comment by EmilyMarkowitz-NOAA** [comment]
Oh weird! Anywho, now closed :)

**Comment by EmilyMarkowitz-NOAA** [comment]
FYI - this code will change a bit for next year, and may even be streamlined as part of another workflow we are developing. Don't use this code next year before checking in :)

**Comment by Erin-Fedewa-NOAA** [comment]
@EmilyMarkowitz-NOAA can you keep me posted on new developments? Would be great to have it in place before ESP products are due to Crab Plan Team, but I know that's a tight turnaround

**Comment by EmilyMarkowitz-NOAA** [comment]
Sure thing! I'll make a point to rewrite this before we go to sea/check that this request is integrated into the possible new workflow. Tagging in @sean-rohan-NOAA for awareness.

**Comment by Erin-Fedewa-NOAA** [comment]
@sean-rohan-NOAA - these products would be for crab ESP's, and I do quite a bit of subsetting based on crab core areas and prey preferences, depending on the stock. So maybe better that I ask for the zero-filled data in it's rawest form? Happy to share the script just to ensure products are being used correctly though of course
