### ISSUE TITLE
[GOA OROX Split Fractions for EGOA with updated species]

### ISSUE THREAD

**Issue by KristenOmori-NOAA** [afsc-gap-products/data-requests#76]
1. Previous data supplied from the RACE bottom trawl survey: "Biomass Fractions in Eastern GOA" data sheet on AKFIN answers
    What it is: I think this is split fractions (or proportions) of the biomass that comes from the West Yak (640) and SE/ EY (650) areas based on the design-based indices of the Eastern GOA (unclear what level of aggregation). 
2. Species and Years: If possible, can I get the split fractions (WY and SE/ EY) in the EGOA for sharpchin, harlequin, redbanded, redstripe, and silvergrey from 2019, 2021, and 2023?
3. Region: Eastern GOA (split fractions between WY and SE/EY)
4. What it is used for: The previous assessment author takes those split fractions from the past 3 surveys (2019, 2021, 2023) to calculate the proportion of biomass that should be allocated to the West Yak (640) and SE/ EY (650) areas (just the Eastern GOA). We are changing the species membership groupings this year, so the groupings posted for Other Rockfish (OROX) are different. 
5. When: Oct. 20th (if possible!) It is for this assessment cycle, which needs to be completed and finalized by the end of Oct, but this goes into the harvest specifications (area allocation). 
6. For: Kristen Omori (@KristenOmori-NOAA, kristen.omori@noaa.gov)

**Comment by Ned-Laman-NOAA** [comment]
Hi Kristen-
Do you want the split fractions for each species you listed separately or corporately. 
I believe that at different times these have been produced as an OROX group or individually by species.

**Comment by KristenOmori-NOAA** [comment]
Hi Ned,
Sharpchin is separate and for the others it can be individual species or
combined in one group. Maybe separate species for ease moving forward?
Thank you again!
Kristen

**Comment by Ned-Laman-NOAA** [comment]
Separate species it is then. I'm getting started on this now. Should have a better since of timeline by early tomorrow.

**Comment by KristenOmori-NOAA** [comment]
Thank you!

**Comment by Ned-Laman-NOAA** [comment]
Hi Kristen. I should be able to get the numbers from 2019, 2021, and 2023 for the 5 rockfish species you indicated by tomorrow morning. I will push them to AKFIN and expect they'll be able to get the new numbers up within 24 hours. If you'd like to have them directly from our Oracle tables sooner, let me know and I can help with that. I'll let you know when the numbers are available.

**Comment by KristenOmori-NOAA** [comment]
Thank you, Ned! I can wait until tomorrow for the numbers, but may reach
out to you if it takes longer. Thank you again for the quick turnaround.

**Comment by kechave** [comment]
Hi Ned-
Similar to Kristin's request, I am needing split fraction biomass estimates for just shortraker rockfish. We are looking at possible management alternatives which unfortunately includes needing to split up WY and EY/SE.  It looks like these are currently combined with rougheye?

Thanks!
katy

**Comment by Ned-Laman-NOAA** [comment]
For Katy's request, I will separate shortraker rockfish from the rougheye-blackspotted rockfish complex and compute split biomass fractions for those two entities. Like with Kristen's request, this currently entails altering the grouping variables in the GOA.GOA_MANAGEMENT_GROUP tables and there is not presently any infrastructure to preserve these changes or the versioning associated with different runs of the estimation code and grouping variables.

Katy provided some additional historical context for the split fractions discussion:
Once trawling was shut down east of 140 W longitude, the "split fraction" was created to allocate sablefish catch in trawl gear in the EGOA.

**Comment by Ned-Laman-NOAA** [comment]
As of today, both Kristen and Katys' requests have been met by me providing them with csvs of the split fractions. Kristen's request has been promoted to AKFIN as of yesterday, but Katy's still needs to be pushed to the public-facing database.
