### ISSUE TITLE
EBS jellyfish (all medusa species) data, 1975 to present

### ISSUE THREAD

**Issue by mb-decker** [afsc-gap-products/data-requests#82]
**Data product requested:** wgtcpue, biomass, temperature, year, stationid, stratum, latitude, longitude, species_code

**Output type:** .csv
 Species Codes 40060, 40061, 40500, 40501, 40502, 40503, 40504, 40505, 40506, 40507, 40508, 40509, 40510, 40511, 40512, 40513, 40515, 40519, 40520, 40560, 40561

**Region** : EBS survey strata = 10, 20, 31, 32, 41, 42, 43, 50, 61, 62
 

**Research team making the request:** Mary Beth Decker, GitHub user = mb-decker, marybeth.decker@yale.edu

**Comment by Duane-Stevenson-NOAA** [comment]
Hi Mary Beth,

Please take a look at the files [here](https://drive.google.com/drive/folders/1aODOWNl2sbZKLzKqJo62hz3rxSIyLiNK?usp=drive_link).

This folder contains 5 files:
EBS_jellies_1982_2023_CPUE.csv -- This is the file with zero-filled CPUE values for each of the species codes in your list.
EBS_jellies_1982_2023_CPUE_group.csv -- This is the file with zero-filled CPUE values for all species codes combined.
EBS_jellies_1982_2023_biomass.csv -- This is the file with biomass values for each of the species codes in your list, for each of your 3 requested areas (AREA_ID codes: 3 = SE middle domain; 4 = NW middle domain; 99901 = entire survey area).
EBS_jellies_1982_2023_biomass_group.csv -- This is the file with biomass values for all species codes combined, for each of your 3 requested areas (AREA_ID codes as above). 
Decker_Jan2023_EBS_jellies.R -- The R script used to generate these files.

Please let me know if any of this doesn't look right, or if you need a different output or format.

Duane
