### ISSUE TITLE
Pollock otolith counts from the GOA "split fraction" historically generated from INPFC areas in SE Alaska

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [afsc-gap-products/data-requests#88]
Cole Monnahan requested pollock otolith specimen counts from the GOA "split fraction." The GOA split fraction is a construct that splits the Yakutat and SEAK INPFC areas into the NMFS Yakutat and SEAK statistical zones which break on longitude 140; the INPFC areas have different breaks. NLaman wrote the following SQLPlus script to generate the otolith specimen counts west of 140 in the INPFC Yakutat area and to the east of 140 in the combined INPFC Yakutat and SEAK area. In addition, this query returns the remaining otolith specimens collected in that survey year from the rest of the GOA survey area.

No additional action is needed at this time 03/15/2024

-- otoliths by cruise and goa fraction
select cruise, nvl(w_of_140,0) w_of_140, nvl(e_of_140,0) e_of_140, nvl(other_goa, 0) rest_of_goa
from
(select cruise, nvl(yak_frac,0) w_of_140, nvl(seak_frac,0) e_of_140
from (
select a.cruise, count(b.hauljoin) yak_frac
from racebase.haul a, racebase.specimen b, goa.goa_strata c
where a.region = 'GOA' and a.cruise >= 199001
and a.abundance_haul = 'Y'
and a.hauljoin = b.hauljoin
and a.stratum = c.stratum
and (a.start_longitude < -140 or a.end_longitude < -140)
and c.inpfc_area = 'Yakutat'
and b.species_code = 21740
and b.age is not null
group by a.cruise
) a
full outer join
(
select a.cruise, count(b.hauljoin) seak_frac
from racebase.haul a, racebase.specimen b, goa.goa_strata c
where a.region = 'GOA' and a.cruise >= 199001
and a.abundance_haul = 'Y'
and a.hauljoin = b.hauljoin
and a.stratum = c.stratum
and (a.start_longitude >= -140 or a.end_longitude >= -140)
and c.inpfc_area in ('Yakutat','Southeastern')
and b.species_code = 21740
and b.age is not null
group by a.cruise
) b
using (cruise)
)
full outer join
(
-- total pollock otoliths from Gulf minus those in the split fraction
select a.cruise, count(b.hauljoin) other_goa
from racebase.haul a, racebase.specimen b, goa.goa_strata c
where a.region = 'GOA' and a.cruise >= 199001
and a.abundance_haul = 'Y'
and a.hauljoin = b.hauljoin
and a.stratum = c.stratum
and (a.start_longitude < -140 or a.end_longitude < -140)
and c.inpfc_area not in ('Yakutat','Southeastern')
and b.species_code = 21740
and b.age is not null
group by a.cruise
)
using (cruise)
order by cruise
/
[otolith_counts.csv](https://github.com/afsc-gap-products/data-requests/files/14620272/otolith_counts.csv)

**Comment by Cole-Monnahan-NOAA** [comment]
Given that there are meaningful numbers of otoliths in this area could you please provide a script to get age compositions for the Gulf west of 140 for all historical years? I.e., including INPFC areas 919, 929, 939, and 949 west of 140W. Thanks!

**Comment by zoyafuso-NOAA** [comment]
Hi @Cole-Monnahan-NOAA ,

In this google drive [folder](https://drive.google.com/drive/folders/1t54vx8Mqj3XhdnYCQY_tup1w9OIPlOGk), you'll see the R script that was committed above as well as a flat file of the agecomps for your review. Let me know if anything comes up.

**Comment by Cole-Monnahan-NOAA** [comment]
@zoyafuso-NOAA I was able to run the script and the new age comps compare well to the existing ones. So that's great, thanks! Is it possible to include a column of biomass by age in the final data set returned?

**Comment by zoyafuso-NOAA** [comment]
Hi @Cole-Monnahan-NOAA ,

Thanks for checking those outputs. As far as biomass by age is concerned, I’m not sure how to do that, let alone do that within gapindex. I am not sure whether we've ever provided something like that in the past. How has that been done in the past? Is there a script that your predecessor was using to calculate that?

**Comment by Ned-Laman-NOAA** [comment]
My first thought is that, while biomass by age is possible, this would be an analytical product and not something to consider a standard survey data product. As such, I do not recommend that Zack spend time adjusting gapindex, which generates our standard products, to create this analytical product.

My next thought is that this is an interesting idea. My understanding is that you'd first have to assign ages to lengths, probably proportionally, then you'd have to convert lengths to weights using the length/weight relationships we have or create new ones. There are a number of potential biases that could be introduced in this process and I think the whole concept is one that would make a great research project that could probably generate a paper and a separate analysis package that could be really valuable to other researchers.

If Zack, or others within GAP, have interest in collaborating on this research with you, Cole, I would be in support of that as long as it fits within the present scope of their activities.

My last thought on the subject is that I've had conversations about this with Stan in the past. He's done this and has some strong opinions about it, so you could touch base with him for another perspective.

**Comment by Cole-Monnahan-NOAA** [comment]
@Ned-Laman-NOAA That's fine, I thought it would be easy. I ask because MACE gives me numbers and biomass by age which I use to get weight at age. For the GAP survey I'll continue to use the specimen data for that. Thanks! Feel free to close the issue.
