### ISSUE TITLE
Temperature profile data request

### ISSUE THREAD

**Issue by KSiwicke** [afsc-gap-products/data-requests#9]
**Data product requested (stratum CPUE, etc.)**: 
Temperature depth profiles at 1-m increments for all available years, such as the data in these profiles https://drive.google.com/file/d/1_BTjGDKm6iUoOoDkkz7nkwaT0gVGuLgj/view?usp=sharing
Can filter if easier: Date, latitude, longitude, temperature, depth of temperature, bottom depth

**Species**:
NA

**Region** (GOA, AI, Bering Sea):
GOA, AI, and Bering Sea

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Kevin Siwicke (@KSiwicke, kevin.siwicke@noaa.gov), ABL - MESA

**Comment by Ned-Laman-NOAA** [comment]
@coleary-noaa @sean-rohan-NOAA 
Is this a request you can fill? The framework for something close to this is in the repo I shared for the ESR temperature chapter last Fall.

**Comment by coleary-noaa** [comment]
I can likely get to this in April, is this an urgent need?

**Comment by Ned-Laman-NOAA** [comment]
I don't believe so. April will do.

**Comment by coleary-noaa** [comment]
it was not, thanks for the reminder! will do ASAP

**Comment by coleary-noaa** [comment]
Data provided to Kevin on 10 May 2022.
