### ISSUE TITLE
[Data product request] Data on zero catches of whiteblotched skate Bathyraja maculata for a full assessment of the distribution and CPUE dynamics of the species 

### ISSUE THREAD

**Issue by IgorGrig** [afsc-gap-products/data-requests#91]
**Data product requested:** 
 Zero catch data, Survey (GOA, Al, BS (shelf and slope), Year (1991-2023), Date Time, Latitude, Longitude, Taxon Confidence.

**Output type:** 
csv

**Species**: Bathyraja maculata

**Region** :
GOA, Al, BS (shelf and slope)

**Research team making the request:**

Igor Grigorov (IgorGrig, grigoroviv@glavrybvod.ru)

**Comment by IgorGrig** [comment]
Data product requested: + depth data
I'm sorry, I forgot to mention it

**Comment by Duane-Stevenson-NOAA** [comment]
Hello Igor,

Please see the attached table, which includes both zero and non-zero catches for B. maculata from all survey regions for the years 1991-2023. Let me know if you have trouble accessing this table, or if the data do not match your request.

Duane
[Bathy_maculata_CPUE.csv](https://github.com/afsc-gap-products/data-requests/files/15395324/Bathy_maculata_CPUE.csv)

**Comment by IgorGrig** [comment]
Dear Dr. Stevenson,
Thank you very much for your help. This information is quite enough for my research.

**Comment by IgorGrig** [comment]
Dear Dr. Stevenson, 
unfortunately, for my research, the values of bottom temperature for zero CPUE are also necessary.
Data product requested: + Bottom Temperature data

**Comment by IgorGrig** [comment]
Dear Dr. Stevenson, 
unfortunately, for my research, the values of bottom temperature for zero CPUE are also necessary.
Data product requested: + Bottom Temperature data

**Comment by Duane-Stevenson-NOAA** [comment]
Hello Igor,

The attached csv file has temperature data included.

Duane
[Bathy_maculata_CPUE.csv](https://github.com/user-attachments/files/15572864/Bathy_maculata_CPUE.csv)

**Comment by IgorGrig** [comment]
Dear Dr. Stevenson,
Thank you very much for your help.
